window.GATE_BANK = window.GATE_BANK || {};
window.GATE_BANK["xl"] = (window.GATE_BANK["xl"] || []).concat([
  { section: "GA", type: "mcq", marks: 1, q: "A shopkeeper marks up an article by 40% above its cost price and then offers a discount of 20%. What is the net profit percentage?", options: { a: "10%", b: "12%", c: "15%", d: "20%" }, correct: ["b"], explain: "If CP = 100, MP = 140. After 20% discount, SP = 140 × 0.8 = 112. Profit = 12% on CP.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 1, q: "Consider the statements: (1) All roses are flowers. (2) Some flowers are red. Which of the following conclusions logically follows?", options: { a: "All roses are red", b: "Some roses may be red", c: "No rose is red", d: "All flowers are roses" }, correct: ["b"], explain: "From the given statements, 'some flowers are red' does not restrict roses. 'Some roses may be red' is the only tentative conclusion not contradicted by the premises.", topic: "Logical Reasoning" },
  { section: "GA", type: "mcq", marks: 1, q: "Find the next term in the series: 3, 7, 15, 31, __", options: { a: "47", b: "55", c: "63", d: "61" }, correct: ["c"], explain: "Each term follows T(n) = 2 × T(n−1) + 1, so the next term is 31 × 2 + 1 = 63. Equivalently, T(n) = 2^(n+1) − 1, giving 2^6 − 1 = 63.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 1, q: "Two numbers are in the ratio 3 : 5. If each number is increased by 6, the new ratio becomes 5 : 7. What is the smaller original number?", options: { a: "6", b: "9", c: "12", d: "15" }, correct: ["b"], explain: "Let numbers be 3x and 5x. Then (3x+6)/(5x+6) = 5/7, giving 21x + 42 = 25x + 30, so x = 3 and the smaller number is 9.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 1, q: "Choose the word most similar in meaning to 'ephemeral'.", options: { a: "Eternal", b: "Fleeting", c: "Robust", d: "Vivid" }, correct: ["b"], explain: "'Ephemeral' means short-lived or transient, which is closest in meaning to 'fleeting'.", topic: "Verbal Ability" },
  { section: "GA", type: "mcq", marks: 2, q: "Pipe A can fill a tank in 20 hours and Pipe B in 30 hours. Drain C can empty the full tank in 60 hours. If all three are opened simultaneously, how many hours will it take to fill the tank?", options: { a: "12", b: "15", c: "18", d: "20" }, correct: ["b"], explain: "Net fill rate = 1/20 + 1/30 − 1/60 = (3+2−1)/60 = 4/60 = 1/15 per hour, so the tank fills in 15 hours.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 2, q: "Eight men can complete a piece of work in 12 days. After working for 4 days, 4 men leave. How many more days will the remaining men take to finish the work?", options: { a: "12", b: "14", c: "16", d: "18" }, correct: ["c"], explain: "Total work = 8 × 12 = 96 man-days. Work done in 4 days = 32 man-days; 64 remain. With 4 men, days needed = 64/4 = 16.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 2, q: "Two trains of lengths 150 m and 200 m run on parallel tracks. When running in the same direction, the faster train crosses the slower in 35 seconds. When running in opposite directions, they cross in 7 seconds. What is the speed of the faster train in km/h?", options: { a: "72", b: "90", c: "108", d: "120" }, correct: ["c"], explain: "Same direction: v₁ − v₂ = 350/35 = 10 m/s. Opposite: v₁ + v₂ = 350/7 = 50 m/s. Solving gives v₁ = 30 m/s = 108 km/h.", topic: "Numerical Aptitude" },
  { section: "GA", type: "mcq", marks: 2, q: "Find the odd one out: 2, 3, 5, 7, 11, 14, 17, 19", options: { a: "3", b: "7", c: "14", d: "17" }, correct: ["c"], explain: "All numbers in the list are prime except 14 (= 2 × 7), which is composite.", topic: "Logical Reasoning" },
  { section: "GA", type: "mcq", marks: 2, q: "A study found that employees working four 10-hour days reported higher satisfaction than those working five 8-hour days, despite the same total hours. However, error rates increased significantly after the 8th hour of work. Which conclusion is best supported?", options: { a: "Longer working days always improve productivity", b: "Four-day work weeks should be universally adopted", c: "Extended work hours may improve satisfaction but reduce accuracy", d: "Error rates are entirely unrelated to work hours" }, correct: ["c"], explain: "The passage directly supports that longer days boosted satisfaction but increased errors after 8 hours. Options (a) and (b) overgeneralise, and (d) contradicts the data.", topic: "Verbal & Reading Comprehension" },

  { section: "CHEM", type: "mcq", marks: 1, q: "What is the hybridization of the central sulfur atom in $\\text{SF}_6$?", options: { a: "$sp^3$", b: "$sp^3d$", c: "$sp^3d^2$", d: "$d^2sp^3$" }, correct: ["c"], explain: "Sulfur in SF₆ is bonded to six fluorine atoms with no lone pairs, requiring six hybrid orbitals → sp³d² hybridization (octahedral geometry).", topic: "Inorganic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 1, q: "Which functional group is present in acetic acid ($\\text{CH}_3\\text{COOH}$)?", options: { a: "Alcohol", b: "Aldehyde", c: "Carboxylic acid", d: "Ketone" }, correct: ["c"], explain: "The –COOH group, comprising a carbonyl and hydroxyl on the same carbon, is the carboxylic acid functional group.", topic: "Organic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 1, q: "The pH of a 0.01 M solution of a strong monoprotic acid (such as HCl) is:", options: { a: "1", b: "2", c: "3", d: "4" }, correct: ["b"], explain: "A strong acid dissociates completely, so [H⁺] = 0.01 M = 10⁻² M, giving pH = −log(10⁻²) = 2.", topic: "Physical Chemistry" },
  { section: "CHEM", type: "mcq", marks: 1, q: "Which of the following elements has the highest first ionization energy?", options: { a: "Na", b: "Mg", c: "Al", d: "Si" }, correct: ["d"], explain: "Across a period, first ionization energy generally increases due to rising nuclear charge. Si (Z = 14) is furthest right among the options and has the highest IE.", topic: "Inorganic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 1, q: "Ethene ($\\text{C}_2\\text{H}_4$) contains:", options: { a: "4 σ bonds and 1 π bond", b: "5 σ bonds and 1 π bond", c: "4 σ bonds and 2 π bonds", d: "5 σ bonds and 0 π bonds" }, correct: ["b"], explain: "C₂H₄ has four C–H σ bonds, one C–C σ bond, and one C=C π bond, totalling 5 σ bonds and 1 π bond.", topic: "Organic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 2, q: "Which reagent is preferred for selectively converting a primary alcohol to an aldehyde without over-oxidation to a carboxylic acid?", options: { a: "$\\text{KMnO}_4$", b: "PCC (Pyridinium chlorochromate)", c: "Jones reagent", d: "$\\text{HNO}_3$" }, correct: ["b"], explain: "PCC is a mild oxidizing agent that stops at the aldehyde stage for primary alcohols. KMnO₄, Jones reagent, and HNO₃ are strong oxidants that carry the oxidation to carboxylic acid.", topic: "Organic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 2, q: "Using Woodward–Fieser rules, which conjugated system would have the longest $\\lambda_{\\max}$ in UV-Vis absorption?", options: { a: "1,3-Butadiene", b: "1,3,5-Hexatriene", c: "1,4-Pentadiene", d: "Ethylene" }, correct: ["b"], explain: "Greater conjugation causes a bathochromic (red) shift. 1,3,5-Hexatriene has three conjugated double bonds versus two in butadiene and none in 1,4-pentadiene (isolated diene).", topic: "Spectroscopy" },
  { section: "CHEM", type: "mcq", marks: 2, q: "The IUPAC name of $\\text{CH}_3\\text{CH(OH)CH}_2\\text{CHO}$ is:", options: { a: "3-Hydroxybutanal", b: "2-Hydroxybutanal", c: "3-Oxobutan-2-ol", d: "1-Hydroxybutan-3-one" }, correct: ["a"], explain: "The aldehyde carbon receives priority as C-1. The –OH group falls on C-3, giving the name 3-hydroxybutanal.", topic: "Organic Chemistry" },
  { section: "CHEM", type: "mcq", marks: 2, q: "For a first-order reaction, the half-life is independent of initial concentration. If the half-life is 10 minutes, what percentage of the reactant remains after 30 minutes?", options: { a: "12.5%", b: "25%", c: "37.5%", d: "50%" }, correct: ["a"], explain: "30 minutes corresponds to 3 half-lives. Fraction remaining = (1/2)³ = 1/8 = 12.5%.", topic: "Physical Chemistry" },
  { section: "CHEM", type: "mcq", marks: 2, q: "What is the initial organic product of the aldol condensation of acetaldehyde ($\\text{CH}_3\\text{CHO}$)?", options: { a: "Butanal", b: "3-Hydroxybutanal", c: "2-Butanone", d: "Ethyl acetate" }, correct: ["b"], explain: "In aldol addition, one acetaldehyde enolizes and attacks another acetaldehyde molecule, forming 3-hydroxybutanal (the aldol product). Dehydration to crotonaldehyde occurs only upon heating.", topic: "Organic Chemistry" },
  { section: "CHEM", type: "msq", marks: 2, q: "Which of the following molecules exhibit hydrogen bonding in the pure state?", options: { a: "$\\text{H}_2\\text{O}$", b: "$\\text{NH}_3$", c: "$\\text{CH}_4$", d: "$\\text{HF}$" }, correct: ["a", "b", "d"], explain: "Hydrogen bonding requires H bonded directly to N, O, or F. H₂O, NH₃, and HF all qualify. CH₄ has only nonpolar C–H bonds and cannot form hydrogen bonds.", topic: "Physical Chemistry" },
  { section: "CHEM", type: "msq", marks: 2, q: "Which spectroscopic technique(s) can reliably distinguish a primary alcohol from a secondary alcohol?", options: { a: "IR spectroscopy", b: "$^1$H NMR spectroscopy", c: "UV-Vis spectroscopy", d: "Flame test" }, correct: ["a", "b"], explain: "IR shows different C–O stretching frequencies (~1050 cm⁻¹ primary vs ~1100 cm⁻¹ secondary). ¹H NMR reveals distinct –CH₂OH vs –CHOH splitting patterns and chemical shifts. UV-Vis and flame tests cannot distinguish them.", topic: "Spectroscopy" },
  { section: "CHEM", type: "msq", marks: 2, q: "According to Hückel's rule, which of the following compounds are aromatic?", options: { a: "Benzene", b: "Cyclobutadiene", c: "Furan", d: "Cyclooctatetraene" }, correct: ["a", "c"], explain: "Aromaticity requires a cyclic, planar, fully conjugated system with 4n+2 π electrons. Benzene (6 π e⁻) and furan (6 π e⁻ with O lone pair contributing) satisfy this. Cyclobutadiene has 4 π e⁻ (anti-aromatic) and cyclooctatetraene adopts a non-planar tub shape (non-aromatic).", topic: "Organic Chemistry" },
  { section: "CHEM", type: "nat", marks: 2, q: "What is the molecular weight of glucose ($\\text{C}_6\\text{H}_{12}\\text{O}_6$) in g/mol? (Enter a numeric value)", ans: 180, tol: 0.01, explain: "Molecular weight = 6(12.01) + 12(1.008) + 6(16.00) ≈ 180.16 g/mol, rounding to 180.", topic: "General Chemistry" },
  { section: "CHEM", type: "nat", marks: 2, q: "Calculate the pH of a 0.1 M acetic acid solution given $K_a = 1.8 \\times 10^{-5}$. (Round to two decimal places)", ans: 2.87, tol: 0.01, explain: "For a weak acid: [H⁺] ≈ √(Ka × C) = √(1.8×10⁻⁶) ≈ 1.342×10⁻³ M. pH = −log(1.342×10⁻³) ≈ 2.87.", topic: "Physical Chemistry" }
]);
