window.GATE_BANK = window.GATE_BANK || {};
window.GATE_BANK['jam'] = (window.GATE_BANK['jam'] || []).concat([
{"section":"C","type":"nat","marks":1,"q":"An enzyme obeying Michaelis–Menten kinetics shows a rate of 25 $\\mu$mol min$^{-1}$ when the substrate concentration equals $K_m$. What is the $V_{max}$ of the reaction in $\\mu$mol min$^{-1}$?","ans":50,"tol":0.01,"unit":"µmol min⁻¹","explain":"At [S] = $K_m$, the Michaelis–Menten equation gives $v = V_{max}/2$. Hence $V_{max} = 2 \\times 25 = 50$ $\\mu$mol min$^{-1}$.","topic":"Enzyme kinetics"},
{"section":"C","type":"nat","marks":1,"q":"A purified enzyme ($M_r$ = 50,000) is present at 0.02 mg mL$^{-1}$ and shows $V_{max}$ = 20 $\\mu$mol min$^{-1}$ per mL of reaction. Calculate the turnover number $k_{cat}$ in min$^{-1}$.","ans":50000,"tol":0.01,"unit":"min⁻¹","explain":"[E]$_{t}$ = (0.02 × 10$^{-3}$ g mL$^{-1}$) / 50,000 g mol$^{-1}$ = 4 × 10$^{-10}$ mol mL$^{-1}$. Since $k_{cat} = V_{max}/[E]_t$ = (20 × 10$^{-6}$) / (4 × 10$^{-10}$) = 50,000 min$^{-1}$.","topic":"Enzyme kinetics"},
{"section":"C","type":"nat","marks":1,"q":"For an enzyme that obeys Michaelis–Menten kinetics, the rate is 48 $\\mu$M min$^{-1}$ when the substrate concentration is four times $K_m$. Compute $V_{max}$ in $\\mu$M min$^{-1}$.","ans":60,"tol":0.01,"unit":"µM min⁻¹","explain":"With [S] = 4$K_m$, $v = V_{max} \\times 4K_m/(4K_m + K_m) = 0.8 V_{max}$. Thus $V_{max} = 48/0.8 = 60$ $\\mu$M min$^{-1}$.","topic":"Enzyme kinetics"},
{"section":"C","type":"nat","marks":1,"q":"How many grams of NaCl (molar mass 58.5 g mol$^{-1}$) are required to prepare 250 mL of a 0.2 M aqueous solution?","ans":2.93,"tol":0.01,"unit":"g","explain":"Moles needed = 0.25 L × 0.2 mol L$^{-1}$ = 0.05 mol; mass = 0.05 × 58.5 = 2.925 g ≈ 2.93 g.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":1,"q":"A 1 M stock solution is diluted 1:10 (one volume stock plus nine volumes solvent) to give S1, and S1 is diluted 1:10 once more to give S2. What is the molarity of S2?","ans":0.01,"tol":0.01,"unit":"M","explain":"Each 1:10 dilution divides concentration by 10; two steps give 1 M × 0.1 × 0.1 = 0.01 M.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":1,"q":"At 25 °C a solution has a hydroxide ion concentration of $1 \\times 10^{-3}$ M. What is its pH?","ans":11,"tol":0.01,"explain":"pOH = −log[$OH^-$] = 3, and pH = 14 − pOH = 11.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":1,"q":"A buffer is prepared from 0.1 M acetic acid and 0.5 M sodium acetate (p$K_a$ of acetic acid = 4.76). Using the Henderson–Hasselbalch equation, calculate the pH of the buffer.","ans":5.46,"tol":0.01,"explain":"pH = p$K_a$ + log([base]/[acid]) = 4.76 + log(0.5/0.1) = 4.76 + 0.699 = 5.46.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":1,"q":"A bacterial culture grows from $1.0 \\times 10^4$ to $6.4 \\times 10^5$ CFU mL$^{-1}$ in 4 hours. What is the doubling (generation) time in minutes?","ans":40,"tol":0.01,"unit":"min","explain":"Ratio = 6.4 × 10$^{5}$/1.0 × 10$^{4}$ = 64 = 2$^{6}$, so 6 doublings occur in 240 min; doubling time = 240/6 = 40 min.","topic":"Microbiology"},
{"section":"C","type":"nat","marks":1,"q":"A culture that starts with 100 cells has a doubling time of 30 minutes. How many cells will be present after 3 hours of exponential growth?","ans":6400,"tol":0.01,"unit":"cells","explain":"Three hours = 6 doubling times; N = 100 × 2$^{6}$ = 100 × 64 = 6400 cells.","topic":"Microbiology"},
{"section":"C","type":"nat","marks":1,"q":"Both parents are carriers (Aa) of an autosomal recessive disorder (penetrance 100%; aa newborns are affected). What is the probability, in percent, that their first child is affected?","ans":25,"tol":0.01,"unit":"%","explain":"An Aa × Aa cross gives 1 AA : 2 Aa : 1 aa, so 1/4 (25%) of children are affected.","topic":"Genetics"},
{"section":"C","type":"nat","marks":2,"q":"In the test cross AaBb × aabb, with the two genes unlinked and assorting independently, what fraction of the progeny has the genotype aaBb?","ans":0.25,"tol":0.01,"explain":"AaBb produces gametes AB, Ab, aB and ab each with probability 1/4; mating with ab gives aaBb only from the aB gamete, i.e. 1/4 = 0.25.","topic":"Genetics"},
{"section":"C","type":"nat","marks":2,"q":"For the dihybrid cross AaBb × AaBb (both genes independently assorting), what is the probability that a randomly chosen offspring shows the dominant phenotype for BOTH traits? Give your answer as a decimal.","ans":0.5625,"tol":0.01,"explain":"The probability of the dominant phenotype at each locus is 3/4, so for both traits (3/4) × (3/4) = 9/16 = 0.5625.","topic":"Genetics"},
{"section":"C","type":"nat","marks":2,"q":"A linear 8.0 kb DNA fragment carries two EcoRI sites located 1.5 kb and 4.5 kb from the left end. After complete digestion, what is the size, in kb, of the largest fragment?","ans":3.5,"tol":0.01,"unit":"kb","explain":"Digestion gives fragments of 1.5 kb, 3.0 kb (4.5 − 1.5) and 3.5 kb (8.0 − 4.5); the largest is 3.5 kb.","topic":"Molecular biology"},
{"section":"C","type":"nat","marks":2,"q":"A double-stranded DNA molecule contains 30% adenine. What percentage of its bases is guanine?","ans":20,"tol":0.01,"unit":"%","explain":"A = T = 30%, so A + T = 60% and G + C = 40%; therefore G = 20%.","topic":"Molecular biology"},
{"section":"C","type":"nat","marks":2,"q":"How many distinct gamete types, with respect to these three gene loci, can an individual of genotype AaBbCC produce, assuming all three genes lie on different chromosomes?","ans":4,"tol":0.01,"explain":"Only the heterozygous loci (Aa and Bb) contribute variation: 2 × 2 = 4 gamete types (ABC, AbC, aBC, abC). The CC locus is monomorphic.","topic":"Genetics"},
{"section":"C","type":"nat","marks":2,"q":"What is the pH of a 0.001 M aqueous solution of HCl at 25 °C, given complete dissociation?","ans":3,"tol":0.01,"explain":"Strong acid dissociates fully, so [H$^+$] = 10$^{-3}$ M and pH = −log(10$^{-3}$) = 3.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":2,"q":"How many moles are contained in $3.011 \\times 10^{23}$ molecules of glucose? (Avogadro's number $N_A = 6.022 \\times 10^{23}$ mol$^{-1}$).","ans":0.5,"tol":0.01,"unit":"mol","explain":"Moles = molecules/$N_A$ = 3.011 × 10$^{23}$ / 6.022 × 10$^{23}$ = 0.5 mol.","topic":"Chemistry"},
{"section":"C","type":"nat","marks":2,"q":"B-DNA adopts 10 base pairs per helical turn, with each turn spanning 3.4 nm. What is the contour length, in nanometres, of a 1200 bp B-DNA molecule?","ans":408,"tol":0.01,"unit":"nm","explain":"Rise per base pair = 3.4/10 = 0.34 nm, so length = 1200 × 0.34 = 408 nm.","topic":"Molecular biology"},
{"section":"C","type":"nat","marks":2,"q":"An enzyme stock has an activity of 1000 U mL$^{-1}$. You take 50 $\\mu$L of the stock but the assay needs only 5 U in a 50 $\\mu$L sample. What fold dilution of the stock is required?","ans":10,"tol":0.01,"explain":"The required concentration is 5 U/50 $\\mu$L = 100 U mL$^{-1}$, which is 10-fold lower than the 1000 U mL$^{-1}$ stock, so a 10-fold dilution is needed.","topic":"Biochemistry"},
{"section":"C","type":"nat","marks":2,"q":"For a reaction at 298 K with equilibrium constant $K_{eq}$ = 10, calculate $\\Delta G°'$ in kJ mol$^{-1}$ using $\\Delta G°' = -RT\\ln K_{eq}$. Take RT = 2.479 kJ mol$^{-1}$ and $\\ln 10 \\approx 2.303$.","ans":-5.71,"tol":0.01,"unit":"kJ/mol","explain":"$\\Delta G°' = -2.479 \\times 2.303 = -5.71$ kJ mol$^{-1}$. The negative value is consistent with an equilibrium that favours products.","topic":"Bioenergetics"}
]);
