/* ============================================================
   CUET PG (SCQP03 / SCQP17) · Question Bank 1 of 2 (40 Qs / 160 marks)
   Domain section D, all MCQ, +4 / -1. Load before app.js.
   ============================================================ */
window.GATE_BANK = window.GATE_BANK || {};
window.GATE_BANK["cuet"] = (window.GATE_BANK["cuet"] || []).concat([

  /* ---------------- CELL BIOLOGY & CELL CYCLE (6) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "During which phase of the eukaryotic cell cycle is the DNA content of a cell doubled via semiconservative replication?",
    options: { a: "G1 phase", b: "S phase", c: "G2 phase", d: "M phase" },
    correct: ["b"],
    explain: "DNA is replicated only during the synthesis (S) phase of interphase. G1 precedes S, G2 follows it, and mitosis (M) is when the replicated chromosomes are partitioned.",
    topic: "Cell Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which cyclin/CDK complex is the principal driver of the G1 to S phase transition in mammalian cells?",
    options: { a: "Cyclin B-CDK1", b: "Cyclin E-CDK2", c: "Cyclin A-CDK1", d: "Cyclin D-CDK2" },
    correct: ["b"],
    explain: "Cyclin E activates CDK2 in late G1, and the complex phosphorylates targets such as Rb to trigger S-phase entry. Cyclin B-CDK1 (MPF) instead drives the G2/M transition.",
    topic: "Cell Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "For every ATP molecule hydrolysed, the plasma membrane Na+/K+-ATPase pumps:",
    options: { a: "3 Na+ out and 2 K+ in", b: "2 Na+ out and 3 K+ in", c: "3 Na+ out and 3 K+ in", d: "2 Na+ out and 2 K+ in" },
    correct: ["a"],
    explain: "The pump moves 3 Na+ out of the cell and 2 K+ into the cell per ATP, generating a net outward positive charge that contributes to the membrane potential.",
    topic: "Membrane Transport" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which of the following molecules crosses a lipid bilayer most readily by simple diffusion?",
    options: { a: "Na+ ion", b: "Glucose", c: "CO2", d: "ATP" },
    correct: ["c"],
    explain: "Small, nonpolar gases such as CO2 and O2 diffuse freely through the hydrophobic bilayer core. Charged ions, polar glucose, and large ATP molecules require transporters or channels.",
    topic: "Membrane Transport" },

  { section: "D", type: "mcq", marks: 4,
    q: "Binding of a ligand to a Gs-coupled GPCR activates which enzyme that synthesises the second messenger cAMP?",
    options: { a: "Phospholipase C", b: "Adenylyl cyclase", c: "Guanylyl cyclase", d: "Protein kinase A" },
    correct: ["b"],
    explain: "The activated Gs alpha subunit stimulates adenylyl cyclase, which converts ATP to cAMP. cAMP then activates protein kinase A (PKA), the downstream effector.",
    topic: "Cell Signaling" },

  { section: "D", type: "mcq", marks: 4,
    q: "Hydrolysis of phosphatidylinositol 4,5-bisphosphate (PIP2) by phospholipase C generates which pair of second messengers?",
    options: { a: "cAMP and cGMP", b: "IP3 and DAG", c: "ATP and Ca2+", d: "GDP and GTP" },
    correct: ["b"],
    explain: "Phospholipase C cleaves PIP2 into inositol trisphosphate (IP3), which releases Ca2+ from the ER, and diacylglycerol (DAG), which activates protein kinase C.",
    topic: "Cell Signaling" },

  /* ---------------- GENETICS & MOLECULAR BIOLOGY (6) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "In a monohybrid cross between two heterozygotes (Aa x Aa), the expected phenotypic ratio of the offspring is:",
    options: { a: "1:1", b: "3:1", c: "9:3:3:1", d: "1:2:1" },
    correct: ["b"],
    explain: "Selfing Aa x Aa yields genotypes AA, Aa, aA, aa in a 1:2:1 genotypic ratio, but with complete dominance the phenotype ratio is 3 dominant : 1 recessive.",
    topic: "Genetics" },

  { section: "D", type: "mcq", marks: 4,
    q: "A point mutation that changes a sense codon into a premature stop codon is called a:",
    options: { a: "missense mutation", b: "nonsense mutation", c: "silent mutation", d: "frameshift mutation" },
    correct: ["b"],
    explain: "A nonsense mutation creates a stop (termination) codon, truncating the protein during translation. Missense changes one amino acid, silent changes none, and frameshift alters the reading frame.",
    topic: "Molecular Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which enzyme synthesises the short RNA primers required to initiate DNA synthesis during replication?",
    options: { a: "Helicase", b: "DNA polymerase III", c: "Primase", d: "Topoisomerase" },
    correct: ["c"],
    explain: "Primase is a specialised RNA polymerase that lays down short RNA primers carrying a free 3'-OH, which DNA polymerases then extend with DNA nucleotides.",
    topic: "Molecular Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which RNA polymerase transcribes protein-coding genes (messenger RNA) in eukaryotic nuclei?",
    options: { a: "RNA polymerase I", b: "RNA polymerase II", c: "RNA polymerase III", d: "Mitochondrial RNA polymerase" },
    correct: ["b"],
    explain: "RNA polymerase II synthesises pre-mRNA, which is processed into mRNA. Pol I makes rRNA (45S) and Pol III makes tRNA and 5S rRNA.",
    topic: "Molecular Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which codon is the standard translation start codon in most eukaryotic mRNAs?",
    options: { a: "UAA", b: "UGA", c: "AUG", d: "AGG" },
    correct: ["c"],
    explain: "AUG, encoding methionine, is the universal start codon that sets the reading frame. UAA and UGA are stop codons, and AGG codes for arginine.",
    topic: "Molecular Biology" },

  { section: "D", type: "mcq", marks: 4,
    q: "In the lac operon of E. coli, which molecule directly inactivates the lac repressor, thereby inducing transcription?",
    options: { a: "Glucose", b: "cAMP", c: "Allolactose", d: "Galactose" },
    correct: ["c"],
    explain: "Allolactose, an isomer of lactose, acts as an inducer by binding the lac repressor and releasing it from the operator, permitting RNA polymerase to transcribe the structural genes.",
    topic: "Gene Regulation" },

  /* ---------------- BIOCHEMISTRY, ENZYMOLOGY & BIOENERGETICS (6) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "In Michaelis-Menten kinetics, the Michaelis constant $K_m$ is defined as the substrate concentration at which the reaction velocity is:",
    options: { a: "Equal to $V_{max}$", b: "Half of $V_{max}$", c: "Double $V_{max}$", d: "One-quarter of $V_{max}$" },
    correct: ["b"],
    explain: "$K_m$ equals the substrate concentration at which the initial velocity is $V_{max}/2$. It reflects substrate affinity, with a lower $K_m$ indicating tighter binding.",
    topic: "Enzymology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which kinetic parameter is characteristically altered by a purely competitive inhibitor?",
    options: { a: "$V_{max}$ decreases", b: "$K_m$ increases", c: "Both $V_{max}$ and $K_m$ decrease", d: "$K_m$ decreases" },
    correct: ["b"],
    explain: "A competitive inhibitor competes with substrate for the active site, so more substrate is needed to reach half-maximal velocity and $K_m$ rises, while $V_{max}$ is unchanged at saturating substrate.",
    topic: "Enzymology" },

  { section: "D", type: "mcq", marks: 4,
    q: "According to the EC classification system, an enzyme that transfers a phosphate group from ATP to a substrate belongs to which class of enzymes?",
    options: { a: "Oxidoreductases", b: "Transferases", c: "Hydrolases", d: "Ligases" },
    correct: ["b"],
    explain: "Transferases catalyse the transfer of functional groups (e.g., phosphate, methyl) between molecules; a kinase is a transferase. Oxidoreductases do redox, hydrolases cleave with water, and ligases join substrates using ATP.",
    topic: "Enzymology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Most of the ATP generated in an aerobic eukaryotic cell is produced by:",
    options: { a: "Glycolysis", b: "Krebs cycle", c: "Oxidative phosphorylation", d: "Substrate-level phosphorylation in the cytosol" },
    correct: ["c"],
    explain: "Approximately 28-34 of the ~36-38 ATP per glucose come from oxidative phosphorylation, where the electron transport chain builds a proton gradient that ATP synthase uses to make ATP.",
    topic: "Bioenergetics" },

  { section: "D", type: "mcq", marks: 4,
    q: "What is the net yield of ATP per molecule of glucose from glycolysis alone?",
    options: { a: "1", b: "2", c: "4", d: "36" },
    correct: ["b"],
    explain: "Glycolysis produces 4 ATP and consumes 2 ATP per glucose, giving a net gain of 2 ATP. The remaining ATP is obtained downstream in the TCA cycle and oxidative phosphorylation.",
    topic: "Bioenergetics" },

  { section: "D", type: "mcq", marks: 4,
    q: "In the citric acid (Krebs) cycle, which two-carbon molecule condenses with oxaloacetate to form citrate?",
    options: { a: "Pyruvate", b: "Acetyl-CoA", c: "Succinyl-CoA", d: "NADH" },
    correct: ["b"],
    explain: "Citrate synthase condenses acetyl-CoA (2C) with oxaloacetate (4C) to form citrate (6C). Pyruvate itself is first decarboxylated to acetyl-CoA by the pyruvate dehydrogenase complex.",
    topic: "Bioenergetics" },

  /* ---------------- MICROBIOLOGY & IMMUNOLOGY (5) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "After Gram staining, Gram-positive bacteria appear:",
    options: { a: "Pink", b: "Purple", c: "Green", d: "Colourless" },
    correct: ["b"],
    explain: "The thick peptidoglycan layer of Gram-positive cells retains the crystal violet-iodine complex during decolourisation, so they stain purple; Gram-negatives appear pink/pink-red.",
    topic: "Microbiology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which immunoglobulin is the first antibody class to appear in serum during a primary immune response?",
    options: { a: "IgG", b: "IgM", c: "IgA", d: "IgE" },
    correct: ["b"],
    explain: "IgM, produced by naive B cells, appears first; a later class switch produces the more abundant high-affinity IgG. IgE mediates allergy, and IgA protects mucosal surfaces.",
    topic: "Immunology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which antibody class is actively transported across the placenta during pregnancy, providing passive immunity to the foetus?",
    options: { a: "IgM", b: "IgG", c: "IgD", d: "IgA" },
    correct: ["b"],
    explain: "IgG crosses the placenta via FcRn receptors, giving the newborn several months of passive immunity. IgM, IgA, IgD, and IgE do not cross efficiently.",
    topic: "Immunology" },

  { section: "D", type: "mcq", marks: 4,
    q: "HIV primarily infects and progressively depletes which cell type, leading to immunodeficiency?",
    options: { a: "CD8+ cytotoxic T cells", b: "CD4+ helper T cells", c: "B lymphocytes", d: "Natural killer cells" },
    correct: ["b"],
    explain: "The virus uses CD4 and a co-receptor to enter CD4+ helper T cells, whose loss cripples both cell-mediated and humoral immunity, producing AIDS.",
    topic: "Immunology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Peptidoglycan, a polymer of glycan chains cross-linked by short peptides, is a major component of the cell wall of:",
    options: { a: "Plants", b: "Fungi", c: "Bacteria", d: "Archaea" },
    correct: ["c"],
    explain: "Bacterial cell walls are built on peptidoglycan (murein), the target of antibiotics like penicillin. Plant and fungal walls use cellulose and chitin, respectively.",
    topic: "Microbiology" },

  /* ---------------- PLANT & ANIMAL PHYSIOLOGY (4) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "The light-dependent reactions of photosynthesis take place in which subcellular compartment of the chloroplast?",
    options: { a: "Stroma", b: "Thylakoid membrane", c: "Inner membrane", d: "Matrix" },
    correct: ["b"],
    explain: "Photosynthetic pigments and the electron transport chain sit in the thylakoid membrane, which generates ATP and NADPH. The Calvin cycle uses these products in the stroma.",
    topic: "Plant Physiology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which plant hormone is primarily responsible for inducing stomatal closure during water stress?",
    options: { a: "Auxin", b: "Gibberellin", c: "Abscisic acid", d: "Cytokinin" },
    correct: ["c"],
    explain: "Abscisic acid (ABA) triggers a signalling cascade that causes guard cells to lose turgor, closing stomata and reducing transpirational water loss.",
    topic: "Plant Physiology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which structure acts as the pacemaker of the mammalian heart, initiating each heartbeat?",
    options: { a: "Atrioventricular node", b: "Sinoatrial node", c: "Purkinje fibres", d: "Bundle of His" },
    correct: ["b"],
    explain: "The sinoatrial (SA) node in the right atrium spontaneously depolarises fastest and sets the cardiac rhythm; the AV node and Purkinje system merely conduct and delay the impulse.",
    topic: "Animal Physiology" },

  { section: "D", type: "mcq", marks: 4,
    q: "The oxygen-carrying respiratory pigment present in vertebrate red blood cells is:",
    options: { a: "Melanin", b: "Hemocyanin", c: "Hemoglobin", d: "Cytochrome c" },
    correct: ["c"],
    explain: "Hemoglobin, a tetramer of globin chains with four heme groups, reversibly binds oxygen for transport. Hemocyanin is a copper-based pigment found in molluscs and arthropods.",
    topic: "Animal Physiology" },

  /* ---------------- ECOLOGY, EVOLUTION & BIOTECHNOLOGY (6) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "A species that has a disproportionately large effect on community structure relative to its abundance or biomass is termed a:",
    options: { a: "Keystone species", b: "Indicator species", c: "Pioneer species", d: "Umbrella species" },
    correct: ["a"],
    explain: "Keystone species (e.g., starfish in intertidal zones) exert control far beyond their numbers; removing them triggers major cascading shifts in the community.",
    topic: "Ecology" },

  { section: "D", type: "mcq", marks: 4,
    q: "The combined variety of genes, species, and ecosystems present in a region is collectively referred to as:",
    options: { a: "Biomass", b: "Biodiversity", c: "Biogeography", d: "Biome" },
    correct: ["b"],
    explain: "Biodiversity spans three levels - genetic, species, and ecosystem diversity. It is measured using indices that account for both richness and relative abundance.",
    topic: "Ecology" },

  { section: "D", type: "mcq", marks: 4,
    q: "For a diallelic locus at Hardy-Weinberg equilibrium with allele frequencies p (A) and q (a), the expected frequency of heterozygotes (Aa) is:",
    options: { a: "$p^2$", b: "$2pq$", c: "$q^2$", d: "$p^2 + q^2$" },
    correct: ["b"],
    explain: "The Hardy-Weinberg expansion of $(p + q)^2$ gives genotype frequencies $p^2$, $2pq$, and $q^2$; the heterozygote class, Aa, has frequency $2pq$.",
    topic: "Evolution" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which enzyme is used to covalently join two DNA fragments by forming phosphodiester bonds during recombinant DNA construction?",
    options: { a: "Restriction endonuclease", b: "DNA ligase", c: "Alkaline phosphatase", d: "Reverse transcriptase" },
    correct: ["b"],
    explain: "DNA ligase seals the nick between adjacent nucleotides of an insert and vector, creating a stable recombinant molecule. Restriction enzymes instead cut DNA at specific sites.",
    topic: "Biotechnology" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which enzyme used in PCR is a thermostable DNA polymerase that survives the ~95 degree C denaturation step?",
    options: { a: "Klenow fragment", b: "Taq polymerase", c: "DNA polymerase I", d: "T4 DNA ligase" },
    correct: ["b"],
    explain: "Taq polymerase, isolated from the thermophile Thermus aquaticus, remains active at high temperature, making the repeated thermal cycling of PCR possible without adding fresh enzyme.",
    topic: "Biotechnology" },

  { section: "D", type: "mcq", marks: 4,
    q: "The lacZ gene in plasmid vectors such as pUC19 enables blue-white screening of recombinants because insertion of foreign DNA into lacZ results in:",
    options: { a: "Blue colonies", b: "White colonies", c: "Green colonies", d: "No colonies" },
    correct: ["b"],
    explain: "Intact lacZ converts the substrate X-gal to a blue product. Inserting a foreign fragment inactivates lacZ, so recombinant clones form white colonies while empty vectors form blue ones.",
    topic: "Biotechnology" },

  /* ---------------- BIOCHEMISTRY TECHNIQUES (4) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "In SDS-PAGE, proteins are separated primarily on the basis of:",
    options: { a: "Native charge", b: "Molecular weight", c: "Isoelectric point", d: "Hydrophobicity" },
    correct: ["b"],
    explain: "SDS denatures proteins and coats them with an even negative charge per unit mass, so mobility depends almost entirely on size. Large proteins migrate more slowly through the gel.",
    topic: "Techniques" },

  { section: "D", type: "mcq", marks: 4,
    q: "Gel filtration (size-exclusion) chromatography separates proteins according to their:",
    options: { a: "Charge", b: "Size or molecular weight", c: "Affinity for a ligand", d: "Hydrophobicity" },
    correct: ["b"],
    explain: "In gel filtration, small molecules enter the porous beads and take a longer path, so they elute later than large molecules, which are excluded and elute first.",
    topic: "Techniques" },

  { section: "D", type: "mcq", marks: 4,
    q: "Southern blotting is used to detect a specific sequence of which molecule?",
    options: { a: "Protein", b: "RNA", c: "DNA", d: "Lipid" },
    correct: ["c"],
    explain: "Southern blotting transfers size-fractionated DNA from a gel to a membrane for probing. Northern and Western blots detect RNA and protein, respectively.",
    topic: "Techniques" },

  { section: "D", type: "mcq", marks: 4,
    q: "Which microscopy method uses a focused laser beam scanned across the specimen to image fluorescently labelled structures in a single optical plane of a living cell?",
    options: { a: "Scanning electron microscopy", b: "Transmission electron microscopy", c: "Confocal laser scanning microscopy", d: "Phase-contrast microscopy" },
    correct: ["c"],
    explain: "Confocal microscopy rejects out-of-focus light with a pinhole, giving sharp optical sections of live, fluorescently labelled cells. EM, by contrast, requires fixed specimens and a vacuum.",
    topic: "Techniques" },

  /* ---------------- MATHEMATICAL BIOLOGY & STATISTICS (3) ---------------- */
  { section: "D", type: "mcq", marks: 4,
    q: "In a self-cross of dihybrids (AaBb x AaBb) with independent assortment, the proportion of offspring showing both dominant phenotypes (A- B-) is:",
    options: { a: "9/16", b: "3/16", c: "1/16", d: "6/16" },
    correct: ["a"],
    explain: "Each dominant phenotype has probability 3/4, so the double-dominant class is $(3/4)^2 = 9/16$. The remaining classes follow the 9:3:3:1 dihybrid ratio.",
    topic: "Genetics" },

  { section: "D", type: "mcq", marks: 4,
    q: "A cross is expected to give a 3:1 phenotypic ratio. If 200 offspring are counted, what is the expected number in the dominant class?",
    options: { a: "50", b: "100", c: "150", d: "75" },
    correct: ["c"],
    explain: "Three-quarters of the offspring fall in the dominant class: $3/4 \\times 200 = 150$. The remaining 50 belong to the recessive class.",
    topic: "Statistical Basis of Genetics" },

  { section: "D", type: "mcq", marks: 4,
    q: "If the probability of an event occurring is p, then the probability that the event does NOT occur is:",
    options: { a: "p - 1", b: "1 - p", c: "p^2", d: "1/p" },
    correct: ["b"],
    explain: "An event and its complement are mutually exclusive and exhaustive, so their probabilities sum to 1; hence P(not E) = 1 - P(E).",
    topic: "Probability" }
]);